import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'he' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Header
    'header.home': 'Accueil',
    'header.guarantees': 'Notre travail',
    'header.pricing': 'Tarif',
    'header.services': 'Formules',
    'header.call': 'Appeler',
    'header.whatsapp': 'WhatsApp',
    
    // Hero
    'hero.slogan': '"Un lavage d\'exception, sans bouger de chez vous."',
    'hero.title': 'Service de lavage automobile',
    'hero.subtitle': 'premium à domicile',
    //'hero.description': 'Service mobile haut de gamme, entièrement manuel avec le souci du détail à chaque étape. Nous venons chez vous avec tout notre équipement professionnel.',
    'hero.cta': 'Réserver maintenant',
    'hero.learn': 'En savoir plus',
    'hero.titlee': "AutoYom",
    'hero.description': "Service de nettoyage automobile premium, directement chez vous.",
    'hero.description2': "Intervention mobile, entièrement réalisée à la main, avec soin et respect pour votre véhicule.",
    'hero.featureHome': "Service à domicile",
    'hero.featureProducts': "Produits professionnels",
    'hero.featureAutonomous': "100% autonome",
    'hero.pricing': "Nos tarifs",
    'hero.imageAlt': "Lavage automobile professionnel",
    
    // Guarantees (ex Why Choose Us)

    'guarantees.title': "Nos garanties",
    'guarantees.highlight': "qualité",
    'guarantees.subtitle': "Votre temps nous importe - L'excellence à votre service avec une approche 100% mobile et professionnelle",
    'guarantees.mobileTitle': "100% Mobile et Autonome",
    'guarantees.mobileDesc': "Nous intervenons partout : domicile, bureau, parking souterrain",
    'guarantees.mobileDetail1': "Réserve d'eau propre embarquée",
    'guarantees.mobileDetail2': "Générateur électrique autonome",
    'guarantees.mobileDetail3': "Rallonges jusqu'à 30 mètres",
    'guarantees.mobileDetail4': "Adaptateurs pour bornes électriques",
    'guarantees.productsTitle': "Produits Professionnels",
    'guarantees.productsDesc': "Nous utilisons exclusivement des marques reconnues",
    'guarantees.productsDetail1': "Green Star (écologique)",
    'guarantees.productsDetail2': "Meguiar's (premium)",
    'guarantees.productsDetail3': "Alchimy7 (professionnel)",
    'guarantees.productsDetail4': "Addict Auto (spécialisé)",
    'guarantees.manualTitle': "Lavage Manuel et Respectueux",
    'guarantees.manualDesc': "Chaque véhicule traité avec le plus grand soin",
    'guarantees.manualDetail1': "Pinceaux et brosses adaptés",
    'guarantees.manualDetail2': "Techniques de lavage sans rayures",
    'guarantees.manualDetail3': "Attention aux détails",
    'guarantees.manualDetail4': "Respect de la carrosserie",
    'guarantees.customTitle': "Service Sur-Mesure",
    'guarantees.customDesc': "Nous adaptons notre intervention à vos besoins",
    'guarantees.customDetail1': "Lavage à l'eau ou vapeur",
    'guarantees.customDetail2': "Horaires flexibles",
    'guarantees.customDetail3': "Devis personnalisés",
    'guarantees.customDetail4': "Conseils d'entretien",
    'guarantees.brand1': "Green Star",
    'guarantees.brand2': "Meguiar's",
    'guarantees.brand3': "Alchimy7",
    'guarantees.brand4': "Addict Auto",
    // Pricing
    'pricing.title': 'Notre',
    'pricing.highlight': 'Travail',
    'pricing.subtitle': 'Découvrez en images l’expérience qui transforme votre quotidien.',
    'pricing.badge': 'Prix pour toutes nos formules selon le véhicule',
    'pricing.compact': 'Citadine / Compacte',
    'pricing.compact.desc': '45 minutes • Véhicules jusqu\'à 4,2m',
    'pricing.sedan': 'Berline / SUV standard',
    'pricing.sedan.desc': '75 minutes • Véhicules standards',
    'pricing.large': 'Grand véhicule / 7 places',
    'pricing.large.desc': '90 minutes • Monospace et grands SUV',
    'pricing.popular': 'Le plus demandé',
    'pricing.reserve': 'Réserver ce tarif',
    'pricing.steps': 'Détails de la prestation - 250sh pour 1h30',
    'pricing.step1': 'Rincage',
    'pricing.step2': 'Shampooing',
    'pricing.step3': 'Lavage a la main',
    'pricing.step4': 'Plastiques cuirs interieurs', 
    'pricing.step5': 'Plastiques textiles interieurs',
    'pricing.step6': 'Nettoyage des vitres intérieures',
    'pricing.step7': 'Depoussierage',
    'pricing.step8': 'Aspirateur interieur',
    'pricing.step9': 'Lavage vitres',
    'pricing.step10': 'Lavage tapis',
    'pricing.note.title': '💎 Pourquoi ce tarif ?',
    'pricing.note.desc': 'Ce prix reflète le temps, la taille du véhicule, les produits utilisés et le niveau de soin apporté à chaque prestation.',
    'pricing.note.detail': 'Nous avons fait le choix de valoriser chaque intervention, même sur des véhicules plus petits. Notre service premium justifie cette approche par la qualité des produits utilisés, le professionnalisme de nos équipes et la commodité du service à domicile.',
    'pricing.mobile.title': 'Service à domicile inclus',
    'pricing.mobile.desc': 'Pas de frais de déplacement dans notre zone d\'intervention',
    'pricing.custom.title': 'Devis personnalisé',
    'pricing.custom.desc': 'Pour les prestations spéciales ou véhicules particuliers',
    
    // Testimonials
    'testimonials.title': 'Quelques avis de nos',
    'testimonials.highlight': 'clients',
    'testimonials.subtitle': 'Découvrez ce que les clients pensent de nous',
    
    // Services
    'services.title': 'Nos',
    'services.highlight': 'Formules de Lavage',
    'services.subtitle': 'Service mobile premium, entièrement manuel avec le souci du détail à chaque étape',
    'services.simple.title': 'Lavage Simple',
    'services.simple.subtitle': 'Intérieur / Extérieur',
    'services.simple.desc': 'Idéal pour un entretien régulier',
    'services.simple.badge': 'Régulier',
    'services.deep.title': 'Lavage Approfondi',
    'services.deep.subtitle': 'Confort et propreté',
    'services.deep.desc': 'Pour un intérieur visiblement plus propre',
    'services.deep.badge': 'Populaire',
    'services.premium.title': 'Lavage Premium',
    'services.premium.subtitle': '& Semi Détail',
    'services.premium.desc': 'Véhicule remis à neuf',
    'services.premium.badge': 'Premium',
    'services.popular': 'Le plus populaire',
    'services.choose': 'Choisir cette formule',
    'services.additional.title': 'Prestations',
    'services.additional.highlight': 'à la carte',
    'services.polishing': 'Application de cire',
    'services.polishing.desc': '100 ₪ • 30 à 60 min',
    'services.waxing': 'Rénovation jantes',
    'services.waxing.desc': '60-100 ₪ • 50 min',
    'services.engine': 'Plastiques intérieurs',
    'services.engine.desc': '60 ₪',
    'services.steam': 'Pressing sièges',
    'services.steam.desc': '350 ₪ • 2 à 3h',
    'services.gel': 'Gel pneus',
    'services.gel.desc': '50 ₪',
    'services.vapor': 'Nettoyage vapeur habitacle fumeurs',
    'services.vapor.desc': '70 ₪ • 40 min',
    'services.quote': 'Demander un devis personnalisé',
    
    // Booking
    'booking.title': 'Réserver',
    'booking.highlight': 'Maintenant',
    'booking.subtitle': 'Réservez en quelques clics à l\'endroit et à l\'horaire qui vous conviennent.',
    'booking.cta': 'Réserver maintenant',
    'booking.description': 'Notre système de réservation en ligne vous permet de choisir facilement votre créneau et le lieu d\'intervention.',

    'booking.flexible': "Planification flexible",
    'booking.chooseSlot': "Choisissez le créneau qui vous convient",
    'booking.atHome': "À votre domicile",
    'booking.comeToYou': "Nous venons directement chez vous ou à votre bureau",
    'booking.instant': "Confirmation immédiate",
    'booking.confirmed': "Réservation confirmée instantanément",
    'booking.onlineTitle': "Réservation en ligne",
    'booking.orContact': "Ou contactez-nous directement",
    
    // Contact
    'contact.title': 'Nous',
    'contact.highlight': 'Contacter',
    'contact.subtitle': 'Une question ? Besoin d\'un devis personnalisé ? Contactez-nous !',
    'contact.name': 'Nom complet',
    'contact.phone': 'Téléphone',
    'contact.location': 'Lieu d\'intervention',
    'contact.vehicle': 'Type de véhicule',
    'contact.message': 'Message (optionnel)',
    'contact.send': 'Envoyer la demande',
    'contact.whatsapp': 'Écrire sur WhatsApp',
    
    // Coming Soon
    'coming.title': 'À Venir',
    'coming.highlight': 'Prochainement',
    'coming.subtitle': 'Découvrez les nouvelles fonctionnalités que nous préparons pour vous',
    'coming.loyalty.title': 'Carte de fidélité virtuelle',
    'coming.loyalty.desc': 'Cumulez des points et bénéficiez d\'avantages exclusifs',
    'coming.videos.title': 'Vidéos avant/après',
    'coming.videos.desc': 'Visualisez le résultat de nos prestations en accéléré',
    'coming.presentation.title': 'Présentation visuelle',
    'coming.presentation.desc': 'Interface interactive pour découvrir nos formules',
    'coming.qr.title': 'QR code personnalisé',
    'coming.qr.desc': 'Réservation rapide via QR code unique',
    
    // Footer
    'footer.tagline': 'Votre voiture, notre fierté',
    'footer.description': 'Service de lavage automobile premium à domicile. Professionnel, mobile et respectueux de votre véhicule.',
    'footer.services.title': 'Nos services',
    'footer.services.simple': 'Lavage simple',
    'footer.services.deep': 'Lavage approfondi',
    'footer.services.premium': 'Lavage premium',
    'footer.contact.title': 'Contact',
    'footer.contact.phone': 'Téléphone',
    'footer.contact.whatsapp': 'WhatsApp',
    'footer.contact.email': 'Email',
    'footer.legal.title': 'Informations légales',
    'footer.legal.terms': 'Conditions d\'utilisation',
    'footer.legal.privacy': 'Politique de confidentialité',
    'footer.legal.mentions': 'Mentions légales',
    'footer.rights': 'Tous droits réservés.',
  },
  he: {
    // Header
    'header.home': 'בית',
    'header.guarantees': 'הבטחות האיכות שלנו',
    'header.pricing': 'תעריפים',
    'header.services': 'נוסחאות שטיפה',
    'header.call': 'התקשר',
    'header.whatsapp': 'WhatsApp',
    
    // Hero
    'hero.slogan': '"המכונית שלך, הגאווה שלנו"',
    'hero.title': 'שירות שטיפת רכבים',
    'hero.subtitle': 'פרימיום עד הבית',
    //'hero.description': 'שירות נייד יוקרתי, ידני לחלוטין עם תשומת לב לכל פרט. אנו מגיעים אליכם עם כל הציוד המקצועי שלנו.',
    'hero.cta': 'הזמן עכשיו',
    'hero.learn': 'למידע נוסף',
    'hero.titlee': 'שטיפת רכב פרימיום עד הבית',
    'hero.description': 'שירות שטיפת רכב יוקרתי עד הבית.',
    'hero.description2': 'הגעה עד אליכם, עבודה ידנית בלבד ושמירה מלאה על הרכב.',
    'hero.featureHome': 'שירות עד הבית',
    'hero.featureProducts': 'מוצרים מקצועיים',
    'hero.featureAutonomous': '100% עצמאי',
    'hero.pricing': 'המחירים שלנו',
    'hero.imageAlt': 'שטיפת רכב מקצועית',

    // Guarantees
    'guarantees.title': 'התחייבויות שלנו',
    'guarantees.highlight': 'איכות',
    'guarantees.subtitle': 'מצוינות בשירותכם עם גישה מקצועית וניידת ב-100%',
    'guarantees.mobileTitle': '100% נייד ועצמאי',
    'guarantees.mobileDesc': 'אנחנו מגיעים לכל מקום: בית, משרד, חניון תת-קרקעי',
    'guarantees.mobileDetail1': 'מיכל מים נקיים מובנה',
    'guarantees.mobileDetail2': 'גנרטור עצמאי',
    'guarantees.mobileDetail3': 'כבלים עד 30 מטר',
    'guarantees.mobileDetail4': 'מתאמים לעמדות טעינה לרכב חשמלי',
    'guarantees.productsTitle': 'מוצרים מקצועיים',
    'guarantees.productsDesc': 'אנחנו משתמשים רק במותגים מוכרים',
    'guarantees.productsDetail1': 'Green Star (אקולוגי)',
    'guarantees.productsDetail2': "Meguiar's (פרימיום)",
    'guarantees.productsDetail3': 'Alchimy7 (מקצועי)',
    'guarantees.productsDetail4': 'Addict Auto (מתמחה)',
    'guarantees.manualTitle': 'שטיפה ידנית וזהירה',
    'guarantees.manualDesc': 'כל רכב מקבל טיפול קפדני',
    'guarantees.manualDetail1': 'מברשות וכלים מותאמים',
    'guarantees.manualDetail2': 'טכניקות שטיפה ללא שריטות',
    'guarantees.manualDetail3': 'תשומת לב לפרטים הקטנים',
    'guarantees.manualDetail4': 'שמירה על שלמות הרכב',
    'guarantees.customTitle': 'שירות מותאם אישית',
    'guarantees.customDesc': 'אנחנו מתאימים את השירות לצרכים שלכם',
    'guarantees.customDetail1': 'שטיפה במים או בקיטור',
    'guarantees.customDetail2': 'שעות גמישות',
    'guarantees.customDetail3': 'הצעות מחיר מותאמות אישית',
    'guarantees.customDetail4': 'טיפים לתחזוקה',
    'guarantees.brand1': 'Green Star',
    'guarantees.brand2': "Meguiar's",
    'guarantees.brand3': 'Alchimy7',
    'guarantees.brand4': 'Addict Auto',
    
    // Pricing
    'pricing.title': 'התעריפים',
    'pricing.highlight': 'שלנו',
    'pricing.subtitle': 'תמחור שקוף לפי סוג הרכב',
    'pricing.badge': 'מחירים לכל הנוסחאות שלנו לפי הרכב',
    'pricing.compact': 'עירוני / קומפקטי',
    'pricing.compact.desc': 'רכבים עד 4.2 מטר',
    'pricing.sedan': 'סדאן / SUV רגיל',
    'pricing.sedan.desc': 'רכבים רגילים',
    'pricing.large': 'רכב גדול / 7 מקומות',
    'pricing.large.desc': 'מונוספייס ו-SUV גדולים',
    'pricing.popular': 'הכי מבוקש',
    'pricing.reserve': 'הזמן תעריף זה',
    'pricing.steps': 'שלבים כלולים',
    'pricing.step1': 'שטיפה ראשונית',
    'pricing.step2': 'שטיפה',
    'pricing.step3': 'ייבוש',
    'pricing.step4': 'ניקוי דלתות מבפנים',
    'pricing.step5': 'שטיפת חישוקים',
    'pricing.step6': 'ניקוי גב מושבים קדמיים',
    'pricing.step7': 'מעבר בדלת',
    'pricing.note.title': '💎 למה התעריפים האלה?',
    'pricing.note.desc': 'המחירים האלה משקפים את הזמן, גודל הרכב, המוצרים המשמשים ורמת הטיפול בכל שירות.',
    'pricing.note.detail': 'בחרנו להעריך כל התערבות, אפילו ברכבים קטנים יותר. השירות הפרימיום שלנו מצדיק את הגישה הזו באיכות המוצרים, המקצועיות של הצוותים והנוחות של השירות בבית.',
    'pricing.mobile.title': 'שירות עד הבית כלול',
    'pricing.mobile.desc': 'ללא עלות נסיעה באזור השירות שלנו',
    'pricing.custom.title': 'הצעת מחיר מותאמת',
    'pricing.custom.desc': 'לשירותים מיוחדים או רכבים מיוחדים',
    
    // Services
    'services.title': 'נוסחאות',
    'services.highlight': 'השטיפה שלנו',
    'services.subtitle': 'שירות נייד פרימיום, ידני לחלוטין עם תשומת לב לכל פרט',
    'services.simple.title': 'שטיפה פשוטה',
    'services.simple.subtitle': 'פנים / חוץ',
    'services.simple.desc': 'אידיאלי לתחזוקה שוטפת',
    'services.simple.badge': 'שוטף',
    'services.deep.title': 'שטיפה מעמיקה',
    'services.deep.subtitle': 'נוחות וניקיון',
    'services.deep.desc': 'לפנים נקי יותר בצורה גלויה',
    'services.deep.badge': 'פופולרי',
    'services.premium.title': 'שטיפה פרימיום',
    'services.premium.subtitle': 'ופירוט',
    'services.premium.desc': 'רכב מחודש',
    'services.premium.badge': 'פרימיום',
    'services.popular': 'הכי פופולרי',
    'services.choose': 'בחר נוסחה זו',
    'services.additional.title': 'שירותים',
    'services.additional.highlight': 'לפי בחירה',
    'services.polishing': 'ליטוש מרכב',
    'services.polishing.desc': 'תיקון שריטות קלות וחמצון',
    'services.waxing': 'ליטוש פרימיום',
    'services.waxing.desc': 'יישום שעווה - ברק והגנה',
    'services.engine': 'ניקוי מנוע',
    'services.engine.desc': 'תא מנוע ללא רבב',
    'services.steam': 'ניקוי מושבים בלחץ',
    'services.steam.desc': 'החל מ-350 ₪ • 2-3 שעות',
    'services.gel': 'ג\'ל צמיגים',
    'services.gel.desc': 'החל מ-50 ₪',
    'services.vapor': 'ניקוי קיטור תא נוסעים מעשנים',
    'services.vapor.desc': '70 ₪ • 40 דקות',
    'services.quote': 'בקש הצעת מחיר מותאמת',
    
    // Booking
    'booking.title': 'הזמן',
    'booking.highlight': 'עכשיו',
    'booking.subtitle': 'הזמינו בכמה קליקים במקום ובזמן שנוח לכם.',
    'booking.cta': 'הזמן עכשיו',
    'booking.description': 'מערכת ההזמנות המקוונת שלנו מאפשרת לכם לבחור בקלות את המועד ומקום ההתערבות.',

    'booking.flexible': 'תכנון גמיש',
    'booking.chooseSlot': 'בחרו את המועד שנוח לכם',
    'booking.atHome': 'בביתכם',
    'booking.comeToYou': 'אנחנו מגיעים ישירות אליכם הביתה או למשרד',
    'booking.instant': 'אישור מיידי',
    'booking.confirmed': 'ההזמנה אושרה באופן מיידי',
    'booking.onlineTitle': 'הזמנה אונליין',
    'booking.orContact': 'או צרו איתנו קשר ישיר',

    
    // Contact
    'contact.title': 'צור',
    'contact.highlight': 'קשר',
    'contact.subtitle': 'שאלה? צריכים הצעת מחיר מותאמת? צרו קשר!',
    'contact.name': 'שם מלא',
    'contact.phone': 'טלפון',
    'contact.location': 'מקום ההתערבות',
    'contact.vehicle': 'סוג הרכב',
    'contact.message': 'הודעה (אופציונלי)',
    'contact.send': 'שלח בקשה',
    'contact.whatsapp': 'כתוב ב-WhatsApp',
    
    // Coming Soon
    'coming.title': 'בקרוב',
    'coming.highlight': '',
    'coming.subtitle': 'גלו את התכונות החדשות שאנו מכינים עבורכם',
    'coming.loyalty.title': 'כרטיס נאמנות וירטואלי',
    'coming.loyalty.desc': 'צברו נקודות ותיהנו מהטבות בלעדיות',
    'coming.videos.title': 'סרטוני לפני/אחרי',
    'coming.videos.desc': 'ראו את התוצאות של השירותים שלנו במהירות מוגברת',
    'coming.presentation.title': 'מצגת חזותית',
    'coming.presentation.desc': 'ממשק אינטראקטיבי לגילוי הנוסחאות שלנו',
    'coming.qr.title': 'QR code מותאם אישית',
    'coming.qr.desc': 'הזמנה מהירה דרך QR code ייחודי',
    
    // Footer
    'footer.tagline': 'המכונית שלכם, הגאווה שלנו',
    'footer.description': 'שירות שטיפת רכבים פרימיום עד הבית. מקצועי, נייד ומכבד את הרכב שלכם.',
    'footer.services.title': 'השירותים שלנו',
    'footer.services.simple': 'שטיפה פשוטה',
    'footer.services.deep': 'שטיפה מעמיקה',
    'footer.services.premium': 'שטיפה פרימיום',
    'footer.contact.title': 'קשר',
    'footer.contact.phone': 'טלפון',
    'footer.contact.whatsapp': 'WhatsApp',
    'footer.contact.email': 'אימייל',
    'footer.legal.title': 'מידע משפטי',
    'footer.legal.terms': 'תנאי שימוש',
    'footer.legal.privacy': 'מדיניות פרטיות',
    'footer.legal.mentions': 'הודעות משפטיות',
    'footer.rights': 'כל הזכויות שמורות.',
  },
  ru: {
    // Header
    'header.home': 'Главная',
    'header.guarantees': 'Наши гарантии качества',
    'header.pricing': 'Тарифы',
    'header.services': 'Формулы мойки',
    'header.call': 'Позвонить',
    'header.whatsapp': 'WhatsApp',
    
    // Hero
    'hero.slogan': '"Ваш автомобиль, наша гордость"',
    'hero.title': 'Услуга мойки автомобилей',
    'hero.subtitle': 'премиум на дому',
    //'hero.description': 'Мобильный премиальный сервис, полностью ручной с вниманием к каждой детали. Мы приезжаем к вам со всем нашим профессиональным оборудованием.',
    'hero.cta': 'Забронировать сейчас',
    'hero.learn': 'Узнать больше',
    'hero.titlee': 'Премиум автомойка на дому',
    'hero.description': 'Элитная услуга мойки автомобиля у вас дома.',
    'hero.description2': 'Мобильное обслуживание, 100% ручная мойка с заботой о вашем авто.',
    'hero.featureHome': 'Обслуживание на дому',
    'hero.featureProducts': 'Профессиональные средства',
    'hero.featureAutonomous': '100% автономно',
    'hero.pricing': 'Наши тарифы',
    'hero.imageAlt': 'Профессиональная автомойка',

    
    // Guarantees
    'guarantees.title': 'Наши гарантии',
    'guarantees.highlight': 'качество',
    'guarantees.subtitle': 'Профессиональный и полностью мобильный сервис премиум-класса',
    'guarantees.mobileTitle': '100% мобильный и автономный',
    'guarantees.mobileDesc': 'Мы работаем везде: дома, в офисе, на подземной парковке',
    'guarantees.mobileDetail1': 'Встроенный резервуар с чистой водой',
    'guarantees.mobileDetail2': 'Автономный генератор',
    'guarantees.mobileDetail3': 'Удлинители до 30 метров',
    'guarantees.mobileDetail4': 'Переходники для зарядных станций',
    'guarantees.productsTitle': 'Профессиональные продукты',
    'guarantees.productsDesc': 'Используем только проверенные бренды',
    'guarantees.productsDetail1': 'Green Star (экологичный)',
    'guarantees.productsDetail2': "Meguiar's (премиум)",
    'guarantees.productsDetail3': 'Alchimy7 (профессиональный)',
    'guarantees.productsDetail4': 'Addict Auto (специализированный)',
    'guarantees.manualTitle': 'Ручная и бережная мойка',
    'guarantees.manualDesc': 'Каждая машина — с особой заботой',
    'guarantees.manualDetail1': 'Специальные кисти и щетки',
    'guarantees.manualDetail2': 'Бережные методы мойки без царапин',
    'guarantees.manualDetail3': 'Внимание к деталям',
    'guarantees.manualDetail4': 'Сохранение лакокрасочного покрытия',
    'guarantees.customTitle': 'Индивидуальный подход',
    'guarantees.customDesc': 'Подбираем услугу под ваши потребности',
    'guarantees.customDetail1': 'Мойка водой или паром',
    'guarantees.customDetail2': 'Гибкий график',
    'guarantees.customDetail3': 'Индивидуальные сметы',
    'guarantees.customDetail4': 'Советы по уходу за авто',
    'guarantees.brand1': 'Green Star',
    'guarantees.brand2': "Meguiar's",
    'guarantees.brand3': 'Alchimy7',
    'guarantees.brand4': 'Addict Auto',

    
    // Pricing
    'pricing.title': 'Наши',
    'pricing.highlight': 'Тарифы',
    'pricing.subtitle': 'Прозрачное ценообразование в зависимости от типа автомобиля',
    'pricing.badge': 'Цены для всех наших формул в зависимости от автомобиля',
    'pricing.compact': 'Городской / Компактный',
    'pricing.compact.desc': '45 минут • Автомобили до 4,2м',
    'pricing.sedan': 'Седан / Стандартный SUV',
    'pricing.sedan.desc': '75 минут • Стандартные автомобили',
    'pricing.large': 'Большой автомобиль / 7 мест',
    'pricing.large.desc': '90 минут • Минивэн и большие SUV',
    'pricing.popular': 'Самый востребованный',
    'pricing.reserve': 'Забронировать этот тариф',
    'pricing.steps': 'Включенные этапы',
    'pricing.step1': 'Предварительная мойка',
    'pricing.step2': 'Мойка',
    'pricing.step3': 'Сушка',
    'pricing.step4': 'Чистка дверей изнутри',
    'pricing.step5': 'Мойка дисков',
    'pricing.step6': 'Чистка спинок передних сидений',
    'pricing.step7': 'Обработка дверных проемов',
    'pricing.note.title': '💎 Почему эти тарифы?',
    'pricing.note.desc': 'Эти цены отражают время, размер автомобиля, используемые продукты и уровень ухода за каждой услугой.',
    'pricing.note.detail': 'Мы сделали выбор ценить каждое вмешательство, даже на меньших автомобилях. Наш премиальный сервис оправдывает этот подход качеством используемых продуктов, профессионализмом наших команд и удобством домашнего сервиса.',
    'pricing.mobile.title': 'Сервис на дому включен',
    'pricing.mobile.desc': 'Без платы за проезд в нашей зоне обслуживания',
    'pricing.custom.title': 'Персональная смета',
    'pricing.custom.desc': 'Для специальных услуг или особых автомобилей',
    
    // Services
    'services.title': 'Наши',
    'services.highlight': 'Формулы Мойки',
    'services.subtitle': 'Мобильный премиум сервис, полностью ручной с вниманием к каждой детали',
    'services.simple.title': 'Простая Мойка',
    'services.simple.subtitle': 'Салон / Кузов',
    'services.simple.desc': 'Идеально для регулярного обслуживания',
    'services.simple.badge': 'Регулярная',
    'services.deep.title': 'Глубокая Мойка',
    'services.deep.subtitle': 'Комфорт и чистота',
    'services.deep.desc': 'Для заметно более чистого салона',
    'services.deep.badge': 'Популярная',
    'services.premium.title': 'Премиум Мойка',
    'services.premium.subtitle': '& Детейлинг',
    'services.premium.desc': 'Автомобиль как новый',
    'services.premium.badge': 'Премиум',
    'services.popular': 'Самая популярная',
    'services.choose': 'Выбрать эту формулу',
    'services.additional.title': 'Услуги',
    'services.additional.highlight': 'по меню',
    'services.polishing': 'Полировка кузова',
    'services.polishing.desc': 'Исправление микроцарапин и окисления',
    'services.waxing': 'Премиум полировка',
    'services.waxing.desc': 'Нанесение воска - блеск и защита',
    'services.engine': 'Мойка двигателя',
    'services.engine.desc': 'Безупречный моторный отсек',
    'services.steam': 'Чистка сидений',
    'services.steam.desc': 'от 350 ₪ • 2-3 часа',
    'services.gel': 'Гель для шин',
    'services.gel.desc': 'от 50 ₪',
    'services.vapor': 'Паровая чистка салона курильщика',
    'services.vapor.desc': '70 ₪ • 40 мин',
    'services.quote': 'Запросить персональную смету',
    
    // Booking
    'booking.title': 'Забронировать',
    'booking.highlight': 'Сейчас',
    'booking.subtitle': 'Забронируйте за несколько кликов в удобном для вас месте и времени.',
    'booking.cta': 'Забронировать сейчас',
    'booking.description': 'Наша система онлайн-бронирования позволяет легко выбрать время и место обслуживания.',
    'booking.flexible': 'Гибкое планирование',
    'booking.chooseSlot': 'Выберите удобное для вас время',
    'booking.atHome': 'У вас дома',
    'booking.comeToYou': 'Мы приедем к вам домой или в офис',
    'booking.instant': 'Мгновенное подтверждение',
    'booking.confirmed': 'Бронирование подтверждено мгновенно',
    'booking.onlineTitle': 'Онлайн-бронирование',
    'booking.orContact': 'Или свяжитесь с нами напрямую',

    
    // Contact
    'contact.title': 'Связаться',
    'contact.highlight': 'с нами',
    'contact.subtitle': 'Вопрос? Нужна персональная смета? Свяжитесь с нами!',
    'contact.name': 'Полное имя',
    'contact.phone': 'Телефон',
    'contact.location': 'Место обслуживания',
    'contact.vehicle': 'Тип автомобиля',
    'contact.message': 'Сообщение (необязательно)',
    'contact.send': 'Отправить запрос',
    'contact.whatsapp': 'Написать в WhatsApp',
    
    // Coming Soon
    'coming.title': 'Скоро',
    'coming.highlight': '',
    'coming.subtitle': 'Откройте для себя новые функции, которые мы готовим для вас',
    'coming.loyalty.title': 'Виртуальная карта лояльности',
    'coming.loyalty.desc': 'Накапливайте баллы и получайте эксклюзивные преимущества',
    'coming.videos.title': 'Видео до/после',
    'coming.videos.desc': 'Посмотрите результаты наших услуг в ускоренном режиме',
    'coming.presentation.title': 'Визуальная презентация',
    'coming.presentation.desc': 'Интерактивный интерфейс для знакомства с нашими формулами',
    'coming.qr.title': 'Персональный QR код',
    'coming.qr.desc': 'Быстрое бронирование через уникальный QR код',
    
    // Footer
    'footer.tagline': 'Ваш автомобиль, наша гордость',
    'footer.description': 'Премиальная услуга мойки автомобилей на дому. Профессионально, мобильно и с уважением к вашему автомобилю.',
    'footer.services.title': 'Наши услуги',
    'footer.services.simple': 'Простая мойка',
    'footer.services.deep': 'Глубокая мойка',
    'footer.services.premium': 'Премиум мойка',
    'footer.contact.title': 'Контакт',
    'footer.contact.phone': 'Телефон',
    'footer.contact.whatsapp': 'WhatsApp',
    'footer.contact.email': 'Email',
    'footer.legal.title': 'Правовая информация',
    'footer.legal.terms': 'Условия использования',
    'footer.legal.privacy': 'Политика конфиденциальности',
    'footer.legal.mentions': 'Правовые упоминания',
    'footer.rights': 'Все права защищены.',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};