import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'fr' | 'he' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  fr: {
    // Header
    'header.home': 'Accueil',
    'header.guarantees': 'Notre travail',
    'header.pricing': 'Tarif',
    'header.services': 'Formules',
    'header.call': 'Appeler',
    'header.whatsapp': 'WhatsApp',
    'reservationPopup.title': 'Combien de véhicules souhaitez-vous laver ?',
    
    // Hero
    'hero.slogan': '"Ta voiture lavée, où tu veux quand tu veux"',
    'hero.title': 'Service de lavage automobile',
    'hero.subtitle': 'premium à domicile',
    //'hero.description': 'Service mobile haut de gamme, entièrement manuel avec le souci du détail à chaque étape. Nous venons chez vous avec tout notre équipement professionnel.',
    'hero.cta': 'Réserver maintenant',
    'hero.learn': 'En savoir plus',
    'hero.titlee': "AutoYom",
    'hero.description': "Service de nettoyage automobile premium, directement chez vous.",
    'hero.description2': "Intervention mobile, entièrement réalisée à la main, avec soin et respect pour votre véhicule.",
    'hero.featureHome': "Service à domicile",
    'hero.featureProducts': "Produits professionnels",
    'hero.featureAutonomous': "100% autonome",
    'hero.pricing': "Nos tarifs",
    'hero.imageAlt': "Lavage automobile professionnel",
    
    // Guarantees (ex Why Choose Us)

    'guarantees.title': "Nos garanties",
    'guarantees.highlight': "qualité",
    'guarantees.subtitle': "Votre temps nous importe - L'excellence à votre service avec une approche 100% mobile et professionnelle",
    'guarantees.mobileTitle': "100% Mobile et Autonome",
    'guarantees.mobileDesc': "Nous intervenons partout : domicile, bureau, parking souterrain",
    'guarantees.mobileDetail1': "Réserve d'eau propre embarquée",
    'guarantees.mobileDetail2': "Générateur électrique autonome",
    'guarantees.mobileDetail3': "Rallonges jusqu'à 30 mètres",
    'guarantees.mobileDetail4': "Adaptateurs pour bornes électriques",
    'guarantees.productsTitle': "Produits Professionnels",
    'guarantees.productsDesc': "Nous utilisons exclusivement des marques reconnues",
    'guarantees.productsDetail1': "Green Star (écologique)",
    'guarantees.productsDetail2': "Meguiar's (premium)",
    'guarantees.productsDetail3': "Alchimy7 (professionnel)",
    'guarantees.productsDetail4': "Addict Auto (spécialisé)",
    'guarantees.manualTitle': "Lavage Manuel et Respectueux",
    'guarantees.manualDesc': "Chaque véhicule traité avec le plus grand soin",
    'guarantees.manualDetail1': "Pinceaux et brosses adaptés",
    'guarantees.manualDetail2': "Techniques de lavage sans rayures",
    'guarantees.manualDetail3': "Attention aux détails",
    'guarantees.manualDetail4': "Respect de la carrosserie",
    'guarantees.customTitle': "Service Sur-Mesure",
    'guarantees.customDesc': "Nous adaptons notre intervention à vos besoins",
    'guarantees.customDetail1': "Lavage à l'eau ou vapeur",
    'guarantees.customDetail2': "Horaires flexibles",
    'guarantees.customDetail3': "Devis personnalisés",
    'guarantees.customDetail4': "Conseils d'entretien",
    'guarantees.brand1': "Green Star",
    'guarantees.brand2': "Meguiar's",
    'guarantees.brand3': "Alchimy7",
    'guarantees.brand4': "Addict Auto",
    // Pricing
    'pricing.title': 'Notre',
    'pricing.highlight': 'Travail',
    'pricing.subtitle': 'Découvrez en images l’expérience qui transforme votre quotidien.',
    'pricing.badge': 'Prix pour toutes nos formules selon le véhicule',
    'pricing.compact': 'Citadine / Compacte',
    'pricing.compact.desc': '45 minutes • Véhicules jusqu\'à 4,2m',
    'pricing.sedan': 'Berline / SUV standard',
    'pricing.sedan.desc': '75 minutes • Véhicules standards',
    'pricing.large': 'Grand véhicule / 7 places',
    'pricing.large.desc': '90 minutes • Monospace et grands SUV',
    'pricing.popular': 'Le plus demandé',
    'pricing.reserve': 'Réserver ce tarif',
    'pricing.steps': 'Détails de la prestation - A partir de 200₪ pour 1h30',
    'pricing.step1': 'Rincage',
    'pricing.step2': 'Shampooing',
    'pricing.step3': 'Lavage a la main',
    'pricing.step4': 'Plastiques cuirs interieurs', 
    'pricing.step5': 'Plastiques textiles interieurs',
    'pricing.step6': 'Nettoyage des vitres intérieures',
    'pricing.step7': 'Depoussierage',
    'pricing.step8': 'Aspirateur interieur',
    'pricing.step9': 'Lavage vitres',
    'pricing.step10': 'Lavage tapis',
    'pricing.note.title': '💎 Pourquoi ce tarif ?',
    'pricing.note.desc': 'Ce prix reflète le temps, la taille du véhicule, les produits utilisés et le niveau de soin apporté à chaque prestation.',
    'pricing.note.detail': 'Nous avons fait le choix de valoriser chaque intervention, même sur des véhicules plus petits. Notre service premium justifie cette approche par la qualité des produits utilisés, le professionnalisme de nos équipes et la commodité du service à domicile.',
    'pricing.mobile.title': 'Service à domicile inclus',
    'pricing.mobile.desc': 'Pas de frais de déplacement dans notre zone d\'intervention',
    'pricing.custom.title': 'Devis personnalisé',
    'pricing.custom.desc': 'Pour les prestations spéciales ou véhicules particuliers',
    'pricing.title.details': 'Détails des tarifs',
    'pricing.table.vehicleType': 'Type de véhicule',
    'pricing.table.price': 'Prix (₪)',  
    'pricing.table.vehicle.standardDirty': 'Voiture standard sale',
    'pricing.table.vehicle.standardVeryDirty': 'Voiture standard très sale',
    'pricing.table.vehicle.jeepDirty': 'Voiture Jeep sale',
    'pricing.table.vehicle.jeepVeryDirty': 'Voiture Jeep très sale',
    
    // Testimonials
    'testimonials.title': 'Quelques avis de nos',
    'testimonials.highlight': 'clients',
    'testimonials.subtitle': 'Découvrez ce que les clients pensent de nous',
    'testimonials.joinUs': 'Rejoignez nos clients satisfaits',
    'testimonials.moreThan100Reviews': 'Plus de 100 avis 5 étoiles',
    
    // Services
    'services.title': 'Nos',
    'services.highlight': 'Formules de Lavage',
    'services.subtitle': 'Service mobile premium, entièrement manuel avec le souci du détail à chaque étape',
    'services.simple.title': 'Lavage Simple',
    'services.simple.subtitle': 'Intérieur / Extérieur',
    'services.simple.desc': 'Idéal pour un entretien régulier',
    'services.simple.badge': 'Régulier',
    'services.deep.title': 'Lavage Approfondi',
    'services.deep.subtitle': 'Confort et propreté',
    'services.deep.desc': 'Pour un intérieur visiblement plus propre',
    'services.deep.badge': 'Populaire',
    'services.premium.title': 'Lavage Premium',
    'services.premium.subtitle': '& Semi Détail',
    'services.premium.desc': 'Véhicule remis à neuf',
    'services.premium.badge': 'Premium',
    'services.popular': 'Le plus populaire',
    'services.choose': 'Choisir cette formule',
    'services.additional.title': 'Prestations',
    'services.additional.highlight': 'à la carte',
    'services.polishing': 'Application de cire',
    'services.polishing.desc': '100 ₪ • 30 à 60 min',
    'services.waxing': 'Rénovation jantes',
    'services.waxing.desc': '60-100 ₪ • 50 min',
    'services.engine': 'Plastiques intérieurs',
    'services.engine.desc': '60 ₪',
    'services.steam': 'Pressing sièges',
    'services.steam.desc': '350 ₪ • 2 à 3h',
    'services.gel': 'Gel pneus',
    'services.gel.desc': '50 ₪',
    'services.vapor': 'Nettoyage vapeur habitacle fumeurs',
    'services.vapor.desc': '70 ₪ • 40 min',
    'services.quote': 'Demander un devis personnalisé',
    
    // Booking
    'booking.title': 'Réserver',
    'booking.highlight': 'Maintenant',
    'booking.subtitle': 'Réservez en quelques clics à l\'endroit et à l\'horaire qui vous conviennent.',
    'booking.cta': 'Réserver maintenant',
    'booking.description': 'Notre système de réservation en ligne vous permet de choisir facilement votre créneau et le lieu d\'intervention.',

    'booking.flexible': "Planification flexible",
    'booking.chooseSlot': "Choisissez le créneau qui vous convient",
    'booking.atHome': "À votre domicile",
    'booking.comeToYou': "Nous venons directement chez vous ou à votre bureau",
    'booking.instant': "Confirmation immédiate",
    'booking.confirmed': "Réservation confirmée instantanément",
    'booking.onlineTitle': "Réservation en ligne",
    'booking.orContact': "Ou contactez-nous directement",
    
    // Contact
    'contact.title': 'Nous',
    'contact.highlight': 'Contacter',
    'contact.subtitle': 'Une question ? Besoin d\'un devis personnalisé ? Contactez-nous !',
    'contact.name': 'Nom complet',
    'contact.phone': 'Téléphone',
    'contact.location': 'Lieu d\'intervention',
    'contact.vehicle': 'Type de véhicule',
    'contact.message': 'Message (optionnel)',
    'contact.send': 'Envoyer la demande',
    'contact.whatsapp': 'Écrire sur WhatsApp',
    
    // Coming Soon
    'coming.title': 'À Venir',
    'coming.highlight': 'Prochainement',
    'coming.subtitle': 'Découvrez les nouvelles fonctionnalités que nous préparons pour vous',
    'coming.loyalty.title': 'Carte de fidélité virtuelle',
    'coming.loyalty.desc': 'Cumulez des points et bénéficiez d\'avantages exclusifs',
    'coming.videos.title': 'Vidéos avant/après',
    'coming.videos.desc': 'Visualisez le résultat de nos prestations en accéléré',
    'coming.presentation.title': 'Présentation visuelle',
    'coming.presentation.desc': 'Interface interactive pour découvrir nos formules',
    'coming.qr.title': 'QR code personnalisé',
    'coming.qr.desc': 'Réservation rapide via QR code unique',
    
    // Footer
    'footer.tagline': 'Votre voiture, notre fierté',
    'footer.description': 'Service de lavage automobile premium à domicile. Professionnel, mobile et respectueux de votre véhicule.',
    'footer.services.title': 'Nos services',
    'footer.services.simple': 'Lavage simple',
    'footer.services.deep': 'Lavage approfondi',
    'footer.services.premium': 'Lavage premium',
    'footer.contact.title': 'Contact',
    'footer.contact.phone': 'Téléphone',
    'footer.contact.whatsapp': 'WhatsApp',
    'footer.contact.email': 'Email',
    'footer.legal.title': 'Informations légales',
    'footer.legal.terms': 'Conditions d\'utilisation',
    'footer.legal.privacy': 'Politique de confidentialité',
    'footer.legal.mentions': 'Mentions légales',
    'footer.rights': 'Tous droits réservés.',
    'footer.openingHours': 'Dim-Ven, horaires flexibles',
    'footer.followUs': 'Suivez-nous',
    'footer.booking': 'Réservation',
    'footer.call': 'Appeler',
    'footer.premiumService': 'Service Premium',
    'footer.professionalEquipment': 'Intervention dans toute la région avec matériel professionnel',
    'footer.reserved': 'Tous droits réservés',
    'footer.professionalService': 'Service professionnel',
    'footer.ecologicalProducts': 'Produits écologiques',
    'footer.satisfactionGuaranteed': 'Satisfaction garantie',
    'footer.serviceAtHome': 'Service à domicile inclus',
    'footer.slogan': 'La qualité à votre porte',
    'footer.contact': 'Contactez-nous',
  },
  he: {
    // Header
    'header.home': 'דף הבית',
    'header.guarantees': 'העבודה שלנו',
    'header.pricing': 'תעריפים',
    'header.services': 'חבילות',
    'header.call': 'התקשר',
    'header.whatsapp': 'וואטסאפ',
    'reservationPopup.title': 'כמה רכבים ברצונך לשטוף?',

    // Hero
    'hero.slogan': '"הרכב שלך נקי, איפה ומתי שתרצה"',
    'hero.title': 'שירות שטיפת רכב',
    'hero.subtitle': 'פרימיום עד הבית',
    'hero.cta': 'הזמן עכשיו',
    'hero.learn': 'למד עוד',
    'hero.titlee': "AutoYom",
    'hero.description': "שירות ניקוי רכב פרימיום, ישירות עד אליך.",
    'hero.description2': "שירות נייד, מתבצע כולו ביד, בקפדנות ובכבוד לרכב שלך.",
    'hero.featureHome': "שירות עד הבית",
    'hero.featureProducts': "מוצרים מקצועיים",
    'hero.featureAutonomous': "100% אוטונומי",
    'hero.pricing': "התעריפים שלנו",
    'hero.imageAlt': "שטיפת רכב מקצועית",

    // Guarantees (ex Why Choose Us)
    'guarantees.title': "ההבטחות שלנו",
    'guarantees.highlight': "איכות",
    'guarantees.subtitle': "הזמן שלך חשוב לנו – מצוינות בשירות עם גישה 100% ניידת ומקצועית",
    'guarantees.mobileTitle': "100% נייד ואוטונומי",
    'guarantees.mobileDesc': "אנחנו מגיעים לכל מקום: בית, משרד, חניון תת־קרקעי",
    'guarantees.mobileDetail1': "מכל מים נקיים מובנה",
    'guarantees.mobileDetail2': "גנרטור חשמלי עצמאי",
    'guarantees.mobileDetail3': "כבלים עד 30 מטר",
    'guarantees.mobileDetail4': "מתאמים לעמדות טעינה",
    'guarantees.productsTitle': "מוצרים מקצועיים",
    'guarantees.productsDesc': "אנו משתמשים אך ורק במותגים מוכרים",
    'guarantees.productsDetail1': "Green Star (אקולוגי)",
    'guarantees.productsDetail2': "Meguiar's (פרימיום)",
    'guarantees.productsDetail3': "Alchimy7 (מקצועי)",
    'guarantees.productsDetail4': "Addict Auto (מתמחה)",
    'guarantees.manualTitle': "שטיפה ידנית ועדינה",
    'guarantees.manualDesc': "כל רכב זוכה לטיפול קפדני",
    'guarantees.manualDetail1': "מברשות וכלים מתאימים",
    'guarantees.manualDetail2': "טכניקות שטיפה ללא שריטות",
    'guarantees.manualDetail3': "תשומת לב לפרטים",
    'guarantees.manualDetail4': "שמירה על הצבע והמרכב",
    'guarantees.customTitle': "שירות מותאם אישית",
    'guarantees.customDesc': "אנו מתאימים את השירות לצרכים שלך",
    'guarantees.customDetail1': "שטיפה במים או בקיטור",
    'guarantees.customDetail2': "זמינות גמישה",
    'guarantees.customDetail3': "הצעות מחיר מותאמות",
    'guarantees.customDetail4': "ייעוץ תחזוקה",
    'guarantees.brand1': "Green Star",
    'guarantees.brand2': "Meguiar's",
    'guarantees.brand3': "Alchimy7",
    'guarantees.brand4': "Addict Auto",

    // Pricing
    'pricing.title': 'העבודה',
    'pricing.highlight': 'שלנו',
    'pricing.subtitle': 'גלו בתמונות את החוויה שמשנה את היום־יום שלכם.',
    'pricing.badge': 'מחירים לכל החבילות לפי סוג הרכב',
    'pricing.compact': 'עירונית / קומפקטית',
    'pricing.compact.desc': '45 דקות • רכבים עד 4.2 מטר',
    'pricing.sedan': 'סדאן / SUV סטנדרטי',
    'pricing.sedan.desc': '75 דקות • רכבים סטנדרטיים',
    'pricing.large': 'רכב גדול / 7 מקומות',
    'pricing.large.desc': '90 דקות • מיניוואנים ו-SUV גדולים',
    'pricing.popular': 'הכי מבוקש',
    'pricing.reserve': 'הזמן במחיר זה',
    'pricing.steps': 'פירוט השירות - החל מ־200₪ עבור שעה וחצי',
    'pricing.step1': 'שטיפה ראשונית',
    'pricing.step2': 'שמפו',
    'pricing.step3': 'שטיפה ידנית',
    'pricing.step4': 'ניקוי פלסטיקים ועור פנימיים',
    'pricing.step5': 'ניקוי פלסטיקים וטקסטיל פנימיים',
    'pricing.step6': 'ניקוי חלונות פנימיים',
    'pricing.step7': 'הסרת אבק',
    'pricing.step8': 'שואב אבק פנימי',
    'pricing.step9': 'ניקוי חלונות חיצוני',
    'pricing.step10': 'ניקוי שטיחים',
    'pricing.note.title': '💎 למה המחיר הזה?',
    'pricing.note.desc': 'המחיר משקף את הזמן, גודל הרכב, החומרים שבהם אנו משתמשים ורמת ההקפדה בכל שירות.',
    'pricing.note.detail': 'בחרנו להעריך כל שירות, גם ברכבים קטנים יותר. השירות הפרימיום שלנו מצדיק זאת הודות לאיכות המוצרים, המקצועיות של הצוותים שלנו ונוחות השירות עד הבית.',
    'pricing.mobile.title': 'שירות עד הבית כלול',
    'pricing.mobile.desc': 'ללא עלות נסיעה באזור הפעילות שלנו',
    'pricing.custom.title': 'הצעת מחיר מותאמת',
    'pricing.custom.desc': 'לשירותים מיוחדים או רכבים ייחודיים',
    'pricing.title.details': 'פירוט המחירים',
    'pricing.table.vehicleType': 'סוג רכב',
    'pricing.table.price': 'מחיר (₪)',
    'pricing.table.vehicle.standardDirty': 'רכב סטנדרטי מלוכלך',
    'pricing.table.vehicle.standardVeryDirty': 'רכב סטנדרטי מלוכלך מאוד',
    'pricing.table.vehicle.jeepDirty': 'רכב ג׳יפ מלוכלך',
    'pricing.table.vehicle.jeepVeryDirty': 'רכב ג׳יפ מלוכלך מאוד',

    // Testimonials
    'testimonials.title': 'כמה חוות דעת מ־',
    'testimonials.highlight': 'הלקוחות שלנו',
    'testimonials.subtitle': 'גלו מה הלקוחות חושבים עלינו',
    'testimonials.joinUs': 'הצטרפו ללקוחות המרוצים שלנו',
    'testimonials.moreThan100Reviews': 'יותר מ־100 חוות דעת 5 כוכבים',
    // Services
    'services.title': 'החבילות',
    'services.highlight': 'שלנו',
    'services.subtitle': 'שירות נייד פרימיום, כולו ידני עם תשומת לב מלאה לכל פרט',
    'services.simple.title': 'שטיפה פשוטה',
    'services.simple.subtitle': 'פנים / חוץ',
    'services.simple.desc': 'אידיאלי לתחזוקה שוטפת',
    'services.simple.badge': 'קבוע',
    'services.deep.title': 'שטיפה מעמיקה',
    'services.deep.subtitle': 'נוחות וניקיון',
    'services.deep.desc': 'לרכב נקי בצורה מורגשת מבפנים',
    'services.deep.badge': 'פופולרי',
    'services.premium.title': 'שטיפת פרימיום',
    'services.premium.subtitle': 'וליטוש חלקי',
    'services.premium.desc': 'הרכב נראה כמו חדש',
    'services.premium.badge': 'פרימיום',
    'services.popular': 'הכי פופולרי',
    'services.choose': 'בחר בחבילה זו',
    'services.additional.title': 'שירותים',
    'services.additional.highlight': 'מותאמים',
    'services.polishing': 'הברקת ווקס',
    'services.polishing.desc': '100 ₪ • 30 עד 60 דקות',
    'services.waxing': 'שיפוץ חישוקים',
    'services.waxing.desc': '60-100 ₪ • 50 דקות',
    'services.engine': 'ניקוי פלסטיקים פנימיים',
    'services.engine.desc': '60 ₪',
    'services.steam': 'ניקוי מושבים בקיטור',
    'services.steam.desc': '350 ₪ • 2 עד 3 שעות',
    'services.gel': 'ג׳ל צמיגים',
    'services.gel.desc': '50 ₪',
    'services.vapor': 'ניקוי אדים לרכבי מעשנים',
    'services.vapor.desc': '70 ₪ • 40 דקות',
    'services.quote': 'בקשת הצעת מחיר מותאמת',
    
    // Booking
    'booking.title': 'הזמנה',
    'booking.highlight': 'עכשיו',
    'booking.subtitle': 'הזמינו בכמה קליקים במקום ובזמן שמתאימים לכם.',
    'booking.cta': 'הזמן עכשיו',
    'booking.description': 'מערכת ההזמנות שלנו מאפשרת לכם לבחור בקלות את המועד והמיקום לביצוע השירות.',

    'booking.flexible': "תזמון גמיש",
    'booking.chooseSlot': "בחרו את המועד שמתאים לכם",
    'booking.atHome': "אצלכם בבית",
    'booking.comeToYou': "אנחנו מגיעים ישירות אליכם או למשרד",
    'booking.instant': "אישור מיידי",
    'booking.confirmed': "ההזמנה מאושרת מיד",
    'booking.onlineTitle': "הזמנה אונליין",
    'booking.orContact': "או צרו איתנו קשר ישירות",

    // Contact
    'contact.title': 'יצירת',
    'contact.highlight': 'קשר',
    'contact.subtitle': 'שאלה? צריכים הצעת מחיר מותאמת? צרו איתנו קשר!',
    'contact.name': 'שם מלא',
    'contact.phone': 'טלפון',
    'contact.location': 'מיקום השירות',
    'contact.vehicle': 'סוג רכב',
    'contact.message': 'הודעה (אופציונלי)',
    'contact.send': 'שלח בקשה',
    'contact.whatsapp': 'כתיבה ב־WhatsApp',

    // Coming Soon
    'coming.title': 'בקרוב',
    'coming.highlight': 'מאוד',
    'coming.subtitle': 'גלו את התכונות החדשות שאנו מכינים עבורכם',
    'coming.loyalty.title': 'כרטיס נאמנות דיגיטלי',
    'coming.loyalty.desc': 'צברו נקודות ותיהנו מהטבות בלעדיות',
    'coming.videos.title': 'סרטוני לפני/אחרי',
    'coming.videos.desc': 'ראו את תוצאות השירותים שלנו במהירות מואצת',
    'coming.presentation.title': 'מצגת חזותית',
    'coming.presentation.desc': 'ממשק אינטראקטיבי להציג את החבילות שלנו',
    'coming.qr.title': 'קוד QR אישי',
    'coming.qr.desc': 'הזמנה מהירה באמצעות קוד QR ייחודי',

    // Footer
    'footer.tagline': 'הרכב שלכם, הגאווה שלנו',
    'footer.description': 'שירות שטיפת רכב פרימיום עד הבית. מקצועי, נייד ומתחשב ברכב שלכם.',
    'footer.services.title': 'השירותים שלנו',
    'footer.services.simple': 'שטיפה פשוטה',
    'footer.services.deep': 'שטיפה מעמיקה',
    'footer.services.premium': 'שטיפת פרימיום',
    'footer.contact.title': 'יצירת קשר',
    'footer.contact.phone': 'טלפון',
    'footer.contact.whatsapp': 'וואטסאפ',
    'footer.contact.email': 'אימייל',
    'footer.legal.title': 'מידע משפטי',
    'footer.legal.terms': 'תנאי שימוש',
    'footer.legal.privacy': 'מדיניות פרטיות',
    'footer.legal.mentions': 'אזכורים משפטיים',
    'footer.rights': 'כל הזכויות שמורות.',
    'footer.openingHours': 'א׳-ה׳, שעות גמישות',
    'footer.followUs': 'עקבו אחרינו',
    'footer.booking': 'הזמנה',
    'footer.call': 'התקשר',
    'footer.premiumService': 'שירות פרימיום',
    'footer.professionalEquipment': 'שירות בכל האזור עם ציוד מקצועי',
    'footer.reserved': 'כל הזכויות שמורות',
    'footer.professionalService': 'שירות מקצועי',
    'footer.ecologicalProducts': 'מוצרים אקולוגיים',
    'footer.satisfactionGuaranteed': 'שביעות רצון מובטחת',
    'footer.serviceAtHome': 'שירות עד הבית כלול',
    'footer.slogan': 'האיכות עד פתח ביתך',
    'footer.contact': 'צור קשר',

  },
  en: {
    // Header
    'header.home': 'Home',
    'header.guarantees': 'Our Work',
    'header.pricing': 'Pricing',
    'header.services': 'Plans',
    'header.call': 'Call',
    'header.whatsapp': 'WhatsApp',

    // Hero
    'hero.slogan': '"Your car cleaned, wherever and whenever you want"',
    'hero.title': 'Car Wash Service',
    'hero.subtitle': 'premium at home',
    'hero.cta': 'Book Now',
    'hero.learn': 'Learn More',
    'hero.titlee': "AutoYom",
    'hero.description': "Premium car cleaning service, directly at your home.",
    'hero.description2': "Mobile service, fully done by hand, with care and respect for your vehicle.",
    'hero.featureHome': "Home Service",
    'hero.featureProducts': "Professional Products",
    'hero.featureAutonomous': "100% Autonomous",
    'hero.pricing': "Our Pricing",
    'hero.imageAlt': "Professional car wash",
    'reservationPopup.title': "How many vehicles would you like to wash?",

    // Guarantees (ex Why Choose Us)
    'guarantees.title': "Our Guarantees",
    'guarantees.highlight': "quality",
    'guarantees.subtitle': "Your time matters to us – Excellence at your service with a 100% mobile and professional approach",
    'guarantees.mobileTitle': "100% Mobile and Autonomous",
    'guarantees.mobileDesc': "We operate everywhere: home, office, underground parking",
    'guarantees.mobileDetail1': "Built-in clean water tank",
    'guarantees.mobileDetail2': "Autonomous electric generator",
    'guarantees.mobileDetail3': "Up to 30-meter extensions",
    'guarantees.mobileDetail4': "Adapters for electric charging stations",
    'guarantees.productsTitle': "Professional Products",
    'guarantees.productsDesc': "We exclusively use reputable brands",
    'guarantees.productsDetail1': "Green Star (eco-friendly)",
    'guarantees.productsDetail2': "Meguiar's (premium)",
    'guarantees.productsDetail3': "Alchimy7 (professional)",
    'guarantees.productsDetail4': "Addict Auto (specialized)",
    'guarantees.manualTitle': "Manual and Gentle Washing",
    'guarantees.manualDesc': "Each vehicle is treated with great care",
    'guarantees.manualDetail1': "Adapted brushes and tools",
    'guarantees.manualDetail2': "Scratch-free washing techniques",
    'guarantees.manualDetail3': "Attention to detail",
    'guarantees.manualDetail4': "Respect for the bodywork",
    'guarantees.customTitle': "Tailor-Made Service",
    'guarantees.customDesc': "We adapt our service to your needs",
    'guarantees.customDetail1': "Water or steam cleaning",
    'guarantees.customDetail2': "Flexible hours",
    'guarantees.customDetail3': "Personalized quotes",
    'guarantees.customDetail4': "Maintenance advice",
    'guarantees.brand1': "Green Star",
    'guarantees.brand2': "Meguiar's",
    'guarantees.brand3': "Alchimy7",
    'guarantees.brand4': "Addict Auto",
    
    // Pricing
    'pricing.title': 'Our',
    'pricing.highlight': 'Work',
    'pricing.subtitle': 'Discover in pictures the experience that transforms your daily life.',
    'pricing.badge': 'Prices for all our plans depending on the vehicle',
    'pricing.compact': 'City / Compact',
    'pricing.compact.desc': '45 minutes • Vehicles up to 4.2m',
    'pricing.sedan': 'Sedan / Standard SUV',
    'pricing.sedan.desc': '75 minutes • Standard vehicles',
    'pricing.large': 'Large Vehicle / 7-Seater',
    'pricing.large.desc': '90 minutes • Minivans and large SUVs',
    'pricing.popular': 'Most Requested',
    'pricing.reserve': 'Book This Rate',
    'pricing.steps': 'Service Details - From 200₪ for 1h30',
    'pricing.step1': 'Rinse',
    'pricing.step2': 'Shampoo',
    'pricing.step3': 'Hand Wash',
    'pricing.step4': 'Interior plastics & leather',
    'pricing.step5': 'Interior plastics & fabrics',
    'pricing.step6': 'Interior window cleaning',
    'pricing.step7': 'Dust removal',
    'pricing.step8': 'Interior vacuum',
    'pricing.step9': 'Exterior window wash',
    'pricing.step10': 'Carpet cleaning',
    'pricing.note.title': '💎 Why this price?',
    'pricing.note.desc': 'This price reflects the time, vehicle size, products used, and the level of care provided in each service.',
    'pricing.note.detail': 'We chose to value every service, even for smaller vehicles. Our premium service justifies this approach through the quality of the products we use, the professionalism of our team, and the convenience of at-home service.',
    'pricing.mobile.title': 'At-Home Service Included',
    'pricing.mobile.desc': 'No travel fees within our service area',
    'pricing.custom.title': 'Custom Quote',
    'pricing.custom.desc': 'For special services or unique vehicles',
    'pricing.title.details': 'Pricing Details',
    'pricing.table.vehicleType': 'Vehicle Type',
    'pricing.table.price': 'Price (₪)',
    'pricing.table.vehicle.standardDirty': 'Standard car – dirty',
    'pricing.table.vehicle.standardVeryDirty': 'Standard car – very dirty',
    'pricing.table.vehicle.jeepDirty': 'Jeep – dirty',
    'pricing.table.vehicle.jeepVeryDirty': 'Jeep – very dirty',

    // Testimonials
    'testimonials.title': 'Some reviews from our',
    'testimonials.highlight': 'clients',
    'testimonials.subtitle': 'See what customers say about us',
    'testimonials.joinUs': 'Join our satisfied customers',
    'testimonials.moreThan100Reviews': 'More than 100 five-star reviews',

    // Services
    'services.title': 'Our',
    'services.highlight': 'Washing Plans',
    'services.subtitle': 'Premium mobile service, fully manual with attention to detail at every step',
    'services.simple.title': 'Simple Wash',
    'services.simple.subtitle': 'Interior / Exterior',
    'services.simple.desc': 'Ideal for regular maintenance',
    'services.simple.badge': 'Regular',
    'services.deep.title': 'Deep Clean',
    'services.deep.subtitle': 'Comfort & cleanliness',
    'services.deep.desc': 'For a visibly cleaner interior',
    'services.deep.badge': 'Popular',
    'services.premium.title': 'Premium Wash',
    'services.premium.subtitle': '& Semi-Detailing',
    'services.premium.desc': 'Vehicle refreshed like new',
    'services.premium.badge': 'Premium',
    'services.popular': 'Most Popular',
    'services.choose': 'Choose this plan',
    'services.additional.title': 'Extra',
    'services.additional.highlight': 'Services',
    'services.polishing': 'Wax application',
    'services.polishing.desc': '100 ₪ • 30 to 60 min',
    'services.waxing': 'Rim restoration',
    'services.waxing.desc': '60-100 ₪ • 50 min',
    'services.engine': 'Interior plastics cleaning',
    'services.engine.desc': '60 ₪',
    'services.steam': 'Seat steam cleaning',
    'services.steam.desc': '350 ₪ • 2 to 3h',
    'services.gel': 'Tire gel',
    'services.gel.desc': '50 ₪',
    'services.vapor': 'Steam cleaning for smoker vehicles',
    'services.vapor.desc': '70 ₪ • 40 min',
    'services.quote': 'Request a custom quote',
    
    // Booking
    'booking.title': 'Book',
    'booking.highlight': 'Now',
    'booking.subtitle': 'Book in just a few clicks at the location and time that suit you.',
    'booking.cta': 'Book Now',
    'booking.description': 'Our online booking system allows you to easily choose your time slot and the service location.',

    'booking.flexible': "Flexible scheduling",
    'booking.chooseSlot': "Choose the time slot that suits you",
    'booking.atHome': "At your home",
    'booking.comeToYou': "We come directly to your home or office",
    'booking.instant': "Instant confirmation",
    'booking.confirmed': "Booking confirmed instantly",
    'booking.onlineTitle': "Online Booking",
    'booking.orContact': "Or contact us directly",

    // Contact
    'contact.title': 'Contact',
    'contact.highlight': 'Us',
    'contact.subtitle': 'A question? Need a custom quote? Contact us!',
    'contact.name': 'Full name',
    'contact.phone': 'Phone',
    'contact.location': 'Service location',
    'contact.vehicle': 'Vehicle type',
    'contact.message': 'Message (optional)',
    'contact.send': 'Send request',
    'contact.whatsapp': 'Write on WhatsApp',

    // Coming Soon
    'coming.title': 'Coming',
    'coming.highlight': 'Soon',
    'coming.subtitle': 'Discover the new features we are preparing for you',
    'coming.loyalty.title': 'Virtual loyalty card',
    'coming.loyalty.desc': 'Earn points and enjoy exclusive benefits',
    'coming.videos.title': 'Before/After videos',
    'coming.videos.desc': 'View the results of our services in fast-forward',
    'coming.presentation.title': 'Visual presentation',
    'coming.presentation.desc': 'Interactive interface to explore our service plans',
    'coming.qr.title': 'Personalized QR code',
    'coming.qr.desc': 'Quick booking via a unique QR code',

    // Footer
    'footer.tagline': 'Your car, our pride',
    'footer.description': 'Premium at-home car wash service. Professional, mobile, and respectful of your vehicle.',
    'footer.services.title': 'Our services',
    'footer.services.simple': 'Simple wash',
    'footer.services.deep': 'Deep wash',
    'footer.services.premium': 'Premium wash',
    'footer.contact.title': 'Contact',
    'footer.contact.phone': 'Phone',
    'footer.contact.whatsapp': 'WhatsApp',
    'footer.contact.email': 'Email',
    'footer.legal.title': 'Legal information',
    'footer.legal.terms': 'Terms of use',
    'footer.legal.privacy': 'Privacy policy',
    'footer.legal.mentions': 'Legal notices',
    'footer.rights': 'All rights reserved.',
    'footer.openingHours': 'Mon-Fri, flexible hours',
    'footer.followUs': 'Follow us',
    'footer.booking': 'Booking',
    'footer.call': 'Call',
    'footer.premiumService': 'Premium Service',
    'footer.professionalEquipment': 'Service throughout the region with professional equipment',
    'footer.reserved': 'All rights reserved',
    'footer.professionalService': 'Professional Service',
    'footer.ecologicalProducts': 'Ecological Products',
    'footer.satisfactionGuaranteed': 'Satisfaction Guaranteed',
    'footer.serviceAtHome': 'At-Home Service Included',
    'footer.slogan': 'Quality at your doorstep',
    'footer.contact': 'Contact Us',
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('he');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};